"""Split SLUS_014.11 into header + payload and emit config/splat.yaml.

Region kinds map to splat subsegment types as:
    code -> asm   (disassembled to .s, reassembled)
    data -> bin   (.incbin; promoted to typed data later, in M6/M8)
    zero -> bin   (1.09 MB of .bss-style zero fill; never worth emitting as text)

Starting everything non-code as `bin` guarantees a byte round-trip, so the
first build can reach a SHA-1 match without waiting on data typing.
"""
import hashlib
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXE = os.path.join(REPO, "disc", "SLUS_014.11")
HDR_LEN = 0x800
VRAM = 0x80010000

raw = open(EXE, "rb").read()
header, payload = raw[:HDR_LEN], raw[HDR_LEN:]

build = os.path.join(REPO, "build")
os.makedirs(build, exist_ok=True)
open(os.path.join(build, "exe_header.bin"), "wb").write(header)
open(os.path.join(build, "main.bin"), "wb").write(payload)

payload_sha1 = hashlib.sha1(payload).hexdigest()
print("payload %d B  sha1 %s" % (len(payload), payload_sha1))

regions = json.load(open(os.path.join(REPO, "config", "regions.json")))

KIND_TO_TYPE = {"code": "asm", "data": "bin", "zero": "bin"}

lines = [
    "# Generated by tools/gen_splat_config.py -- edit regions.json instead.",
    "name: Yu-Gi-Oh! Forbidden Memories (USA)",
    "sha1: %s" % payload_sha1,
    "options:",
    "  platform: psx",
    "  basename: main",
    "  base_path: ..",
    "  target_path: build/main.bin",
    "  asm_path: asm",
    "  src_path: src",
    "  build_path: build",
    "  asset_path: assets",
    "  ld_script_path: linker_scripts/main.ld",
    "  symbol_addrs_path: config/symbol_addrs.txt",
    "  find_file_boundaries: True",
    "  compiler: GCC",
    "  section_order: ['.text', '.data', '.rodata', '.bss']",
    "  disassemble_all: True",
    "segments:",
    "  - name: main",
    "    type: code",
    "    start: 0x0",
    "    vram: 0x%08X" % VRAM,
    "    subsegments:",
]

for r in regions:
    typ = KIND_TO_TYPE[r["kind"]]
    name = "%s_%06X" % (r["kind"], r["start"])
    lines.append("      - [0x%06X, %s, %s]" % (r["start"], typ, name))

lines.append("  - [0x%06X]" % len(payload))
lines.append("")

cfg = os.path.join(REPO, "config", "splat.yaml")
open(cfg, "w").write("\n".join(lines))
print("wrote %s (%d subsegments)" % (cfg, len(regions)))

for p in ("symbol_addrs.txt", "undefined_syms.txt"):
    path = os.path.join(REPO, "config", p)
    if not os.path.exists(path):
        open(path, "w").write("")
